### ISSUE TITLE
Out of memory errors with node s3-deploy — suggestion to use aws s3 cli instead

### ISSUE THREAD

**Issue by pratheekrebala** [PublicI/app-generator#22]
Could you switch the S3 client being used for `yarn push` to use the native S3 client? I'm getting out of memory errors with the current node client.

`aws s3 sync --acl="public-read" ./dist/ s3://apps.publicintegrity.org/$npm_package_name/`

Also, assuming this switch is made - we can also use the aws cli to trigger a cloudfront cache invalidation:

 `aws cloudfront create-invalidation --distribution-id "[REDACTED]" --paths /$npm_package_name/*` 

so that the cloudfront cache is busted and the latest version shows up on apps.publicintegrity.org

**Comment by chriszs** [comment]
Thanks for the detailed suggestion! Sorry you experienced problems with the new approach. I was debating whether to keep it in a branch for a while until we'd thoroughly tested it.

My guess is that you're encountering memory issues because you're uploading a lot of tiles and s3-deploy isn't well-optimized for that scenario. This is a problem specific to mapping that I also encountered when using gulp.

Three potential problems with the suggestion:
1. I got rid of gulp in part to minimize the number of external dependencies required to set up and deploy. I noticed new people were struggling to set everything up.
2. No gzip. This makes a huge difference in the download size and user experience.
3. Right now we're using the same method to deploy locally as we're using on the CI. To achieve the same result with this solution would require a different approach.

Technically, we could do CloudFront invalidation with s3-deploy, but we're using a short cache lifetime instead, so that's either a non-issue or a separate issue.

There may be a way around some of these problems, and if so it might make sense to do what you're suggesting. I could also see a potential "aws-cli-push" or "push-native" alternate script entry in package.json.

In general, though, the role of the template is to provide a basic setup that works for most scenarios and that can be modified to meet others. If we're running into this relatively rarely, we may want to handle it on the specific project.

**Comment by chriszs** [comment]
Changed the title of this issue to reflect the problem — out of memory errors — as well as the suggested solution.

**Comment by chriszs** [comment]
A couple miscellaneous notes:

For whole country maps with multiple zoom levels, even aws cli takes too long. I've used [s3-parallel-put](https://github.com/mishudark/s3-parallel-put) successfully for this in the past. The node equivalent appears to be [pput](https://www.npmjs.com/package/pput) but I don't know if it's any good.

We may want to consider filing the memory errors upstream in the [s3-deploy](https://github.com/import-io/s3-deploy) repo. The project appears to be semi-active in that maintainers are responding to issues and merging pull requests.

CloudFront can [now gzip files for us](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html), if we don't want to gzip them ourselves. This may be a potential solution to problem number 3.

**Comment by pratheekrebala** [comment]
Is there any specific reason to use a 3rd party tool like `s3-deploy` v/s using the native aws cli supported by Amazon?

The out of memory issues are happening because the client tries to load all the available files into memory before doing any uploads. This is obviously an inefficient way of uploading data. The use of `s3-parallel-put` is pretty good for uploading a lot of files fast, but `aws s3 sync` works pretty well for my use case of uploading tiles of the entire north-eastern united states from zoom levels 1-8.

**Comment by chriszs** [comment]
I gave three reasons.

**Comment by chriszs** [comment]
Added alternate `npm run aws-publish` command to template which uses the aws CLI.

**Comment by chriszs** [comment]
(Also turned on gzipping on CloudFront. We'll see how that goes.)
